# Generated by Django 2.1.15 on 2020-02-17 05:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateField(default=django.utils.timezone.now)),
                ('comentario', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, null=True)),
                ('foto', models.ImageField(null=True, upload_to='images/deportes')),
            ],
        ),
        migrations.CreateModel(
            name='DeportesDeportistas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.ForeignKey(db_column='id_deporte', null=True, on_delete=django.db.models.deletion.CASCADE, to='tokio.Deportes')),
            ],
        ),
        migrations.CreateModel(
            name='Deportistas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('lugarNac', models.CharField(max_length=100)),
                ('fechaNac', models.DateField()),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('estatura', models.FloatField()),
                ('foto', models.ImageField(upload_to='images/deportistas')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(max_length=100)),
                ('linkVideo', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('deporte', models.ForeignKey(db_column='id_deporte', null=True, on_delete=django.db.models.deletion.CASCADE, to='tokio.Deportes')),
            ],
        ),
        migrations.AddField(
            model_name='deportistas',
            name='entrenador',
            field=models.ForeignKey(db_column='id_entrenador', null=True, on_delete=django.db.models.deletion.CASCADE, to='tokio.Entrenadores'),
        ),
        migrations.AddField(
            model_name='deportesdeportistas',
            name='deportista',
            field=models.ForeignKey(db_column='id_deportistas', null=True, on_delete=django.db.models.deletion.CASCADE, to='tokio.Deportistas'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='estudiante',
            field=models.ForeignKey(db_column='id_estudiante', null=True, on_delete=django.db.models.deletion.CASCADE, to='tokio.Estudiante'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='participacion',
            field=models.ForeignKey(db_column='id_participacion', null=True, on_delete=django.db.models.deletion.CASCADE, to='tokio.Participaciones'),
        ),
    ]
